# Generated by Django 4.2 on 2024-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('B', 'Bakso'), ('JL', 'Jajanan Lokal'), ('JN', 'Jajanan Non-Lokal')], max_length=2),
        ),
    ]
